# Generated by Django 2.0.2 on 2018-04-05 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_auto_20180402_1414'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='specialty',
            field=models.CharField(default=True, max_length=50),
        ),
    ]
