# Generated by Django 2.0.2 on 2018-04-05 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_post_specialty'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='location',
            field=models.BigIntegerField(default='0', max_length=10),
        ),
    ]
