# Generated by Django 2.0.2 on 2018-04-05 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_auto_20180405_1740'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='location',
            field=models.BigIntegerField(default='0'),
        ),
    ]
