# Generated by Django 2.0.2 on 2018-04-05 14:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0006_auto_20180405_1741'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='location',
            new_name='plan',
        ),
    ]
