# Generated by Django 2.0.2 on 2018-04-05 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0007_auto_20180405_1749'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='plan_rez',
            field=models.BigIntegerField(default='0'),
        ),
    ]
