# Generated by Django 2.0.2 on 2018-04-19 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0009_auto_20180414_1008'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='plan_all',
            field=models.BigIntegerField(default='0'),
        ),
    ]
