# Generated by Django 2.0.2 on 2018-04-19 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0011_auto_20180420_0122'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='plan_defect',
            field=models.BigIntegerField(default='0'),
        ),
    ]
