# Generated by Django 2.0.2 on 2018-04-19 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0012_post_plan_defect'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='plan_defect_all',
            field=models.BigIntegerField(default='0'),
        ),
    ]
