# Generated by Django 2.0.2 on 2018-04-19 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0013_post_plan_defect_all'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='cex_defect_all',
            field=models.BigIntegerField(default='0'),
        ),
        migrations.AddField(
            model_name='post',
            name='cex_plan_all',
            field=models.BigIntegerField(default='0'),
        ),
    ]
