# Generated by Django 2.0.2 on 2018-04-20 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0014_auto_20180420_0246'),
    ]

    operations = [
        migrations.CreateModel(
            name='AllRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=100)),
                ('cex_result', models.BigIntegerField(default='0')),
                ('cex_plan_result', models.BigIntegerField(default='0')),
                ('cex_befect_result', models.BigIntegerField(default='0')),
            ],
        ),
    ]
