# Generated by Django 2.0.2 on 2018-04-22 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0016_remove_post_plan_defect'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='plan_defect',
            field=models.BigIntegerField(default='0'),
        ),
    ]
