# Generated by Django 2.0.2 on 2018-04-22 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0018_auto_20180422_1548'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='plan',
            field=models.BigIntegerField(default='0', null=True),
        ),
    ]
