# Generated by Django 2.1.7 on 2019-02-26 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0019_auto_20180422_1624'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hashtag',
            name='post',
        ),
        migrations.AlterField(
            model_name='post',
            name='plan',
            field=models.BigIntegerField(default='0'),
        ),
        migrations.AlterField(
            model_name='post',
            name='plan_defect',
            field=models.BigIntegerField(blank=True, default='0'),
        ),
        migrations.DeleteModel(
            name='HashTag',
        ),
    ]
