# Generated by Django 2.1.7 on 2019-03-26 21:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0020_auto_20190226_2050'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AllRequest',
        ),
    ]
