# Generated by Django 2.2.1 on 2019-06-01 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0021_delete_allrequest'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='specialty',
        ),
        migrations.AlterField(
            model_name='post',
            name='cex_defect_all',
            field=models.PositiveIntegerField(default='0'),
        ),
        migrations.AlterField(
            model_name='post',
            name='cex_plan_all',
            field=models.PositiveIntegerField(default='0'),
        ),
        migrations.AlterField(
            model_name='post',
            name='plan',
            field=models.PositiveIntegerField(default='0'),
        ),
        migrations.AlterField(
            model_name='post',
            name='plan_all',
            field=models.PositiveIntegerField(default='0'),
        ),
        migrations.AlterField(
            model_name='post',
            name='plan_clock',
            field=models.PositiveIntegerField(default='0'),
        ),
        migrations.AlterField(
            model_name='post',
            name='plan_clock_all',
            field=models.PositiveIntegerField(default='0'),
        ),
        migrations.AlterField(
            model_name='post',
            name='plan_clock_rez',
            field=models.PositiveIntegerField(default='0'),
        ),
        migrations.AlterField(
            model_name='post',
            name='plan_defect',
            field=models.PositiveIntegerField(blank=True, default='0'),
        ),
        migrations.AlterField(
            model_name='post',
            name='plan_defect_all',
            field=models.PositiveIntegerField(default='0'),
        ),
        migrations.AlterField(
            model_name='post',
            name='plan_rez',
            field=models.PositiveIntegerField(default='0'),
        ),
        migrations.AlterField(
            model_name='post',
            name='plan_rez_all',
            field=models.PositiveIntegerField(default='0'),
        ),
    ]
