# Generated by Django 2.2.1 on 2019-06-01 17:24

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0022_auto_20190601_1711'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='specialty',
            field=models.CharField(default=True, max_length=50, validators=[django.core.validators.RegexValidator('^[а-яА-Яa-zA-Z]*$', 'Only alphanumeric characters are allowed.', code='invalid_specialty')]),
        ),
        migrations.AlterField(
            model_name='post',
            name='text',
            field=models.CharField(max_length=100, validators=[django.core.validators.RegexValidator('^[а-яА-Яa-zA-Z]*$', 'Only alphanumeric characters are allowed.', code='invalid_name')]),
        ),
    ]
