# Generated by Django 2.2.1 on 2019-06-01 18:00

import django.contrib.auth.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0025_auto_20190601_1741'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='specialty',
            field=models.CharField(default=True, max_length=50, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()]),
        ),
        migrations.AlterField(
            model_name='post',
            name='text',
            field=models.CharField(max_length=100),
        ),
    ]
