# Generated by Django 2.2.1 on 2019-06-01 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0026_auto_20190601_1800'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='specialty',
            field=models.CharField(default=True, max_length=50),
        ),
    ]
